### ISSUE TITLE
Update Godots

### ISSUE THREAD

**Issue by coffandro** [flathub/io.github.MakovWait.Godots#3]
The latest version of [Godots is v1.3 stable](https://github.com/MakovWait/godots/releases/tag/v1.3.stable), there have been multiple new features introduced and a redesign.

It would be nice to have this Flatpak updated to the newest release

**Comment by GreatNovaDragon** [comment]
At least with Godots v1.3 and Godot 4.3, a build needs to re-import everything on first launch, cause the .godot folder is not included, which fails builds.

 [It looks like Godot v4.4 will fix that.](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-2/#error-less-first-project-import)
